export const INITIAL_TSV_DATA = `Datum	Dag	Stad / Regio	Verblijf	Verblijf link	Verblijf adres / pin	Google maps link	Activiteit	Activiteitstype	Activiteit locatie	Starttijd	Verzameltijd	Vertrek vanaf	Vervoer	Reistijd	Melding	Avondmelding (template)	Beschrijving
21 Jan	Woensdag	City 1	Airport	x	x	x	Activity 1	flight	Location 1	18:10	16:00	x	Transport 1	70	16:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde vluchtbeschrijving. Vertrek- en aankomstinfo staan in de planning.
21 Jan	Woensdag	City 2	Airport	x	x	x	Activity 2	flight	Location 2	22:15	x	x	Transport 1	705	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde vluchtbeschrijving. Vertrek- en aankomstinfo staan in de planning.
22 Jan	Donderdag	City 3	Accommodation 1	x	Address 1	x	Activity 3	tour	Location 3	09:00	08:15	Meeting Point 1	Transport 2	30	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
23 Jan	Vrijdag	City 3	Accommodation 1	x	Address 1	x	Activity 4	tour	Location 4	11:00	11:30	Verblijf	Transport 2	45	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
23 Jan	Vrijdag	City 3	Accommodation 1	x	Address 1	x	Activity 5	event	TBA	17:00	TBA	Verblijf	Transport 2	TBA	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
24 Jan	Zaterdag	City 3	Accommodation 1	x	Address 1	x	Activity 6	hike	Location 5	05:00	TBD	Verblijf	Transport 3	TBA	09:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
24 Jan	Zaterdag	City 3	Accommodation 1	x	Address 1	x	Activity 5	event	TBA	11:00	TBD	Verblijf	Transport 2	TBA	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
24 Jan	Zaterdag	City 3	Accommodation 1	x	Address 1	x	Activity 7	event	Location 6	21:00	19:30	Verblijf	Transport 2	45	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
25 Jan	Zondag	City 4	Accommodation 2	x	Address 2	x	Activity 8	hike	Location 7	07:15	07:00	Verblijf	Transport 4	150	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
26 Jan	Maandag	City 4	Accommodation 3	x	Address 3	x	Activity 9	hike	Location 8	08:30	08:00	Meeting Point 2	Transport 5	360	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
26 Jan	Maandag	City 5	Accommodation 3	x	Address 3	x	Activity 10	travel	Location 9	17:00	16:30	Meeting Point 3	Transport 6	180	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
27 Jan	Dinsdag	City 6	Accommodation 3	x	Address 3	x	Activity 11	tour	Location 10	11:30	11:15	Meeting Point 4	Transport 7	5	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
28 Jan	Woensdag	City 6	Accommodation 3	x	Address 3	x	Activity 12	free_day	x	x	x	Verblijf	x	x	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
29 Jan	Donderdag	City 7	Accommodation 4	x	Address 4	x	Activity 13	travel	Location 10	10:00	09:45	Meeting Point 4	Transport 8	330	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
29 Jan	Donderdag	City 7	Accommodation 4	x	Address 4	x	Activity 14	event	Location 11	19:00	x	Verblijf	Transport 7	x	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
30 Jan	Vrijdag	City 7	Accommodation 4	x	Address 4	x	Activity 15	event	Location 12	11:00	TBA	Meeting Point 5	Transport 9	30	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
31 Jan	Zaterdag	City 7	Accommodation 4	x	Address 4	x	Activity 16	free_day	Location 12	11:00	TBA	Meeting Point 5	Transport 9	TBA	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde beschrijving van de activiteit. Details en tijden staan in de planning.
1 Feb	Zondag	City 8	Airport	x	x	x	Activity 17	flight	Location 13	15:40	x	x	Transport 1	915	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde vluchtbeschrijving. Vertrek- en aankomstinfo staan in de planning.
2 Feb	Maandag	City 8	Airport	x	x	x	Activity 18	flight	Location 2	12:40	x	x	Transport 1	70	21:00	Morgen staat er een activiteit gepland. Check de app voor tijden en locatie.	Geanonimiseerde vluchtbeschrijving. Vertrek- en aankomstinfo staan in de planning.`;
